export const ADD_NODE = "ADD_NODE";
export const REMOVE_NODE = "REMOVE_NODE";
export const MODIFY_NODE = "MODIFY_NODE";
export const SET_ACTIVE_NODE = "SET_ACTIVE_NODE";

export const CREATE_CONNECTION = "CREATE_CONNECTION";
export const UPDATE_NODE_CONNECTIONS = "UPDATE_NODE_CONNECTIONS";
export const DELETE_NODE_CONNECTIONS = "DELETE_NODE_CONNECTIONS";

export const SET_WORKSPACE_TRANSLATE_X = "SET_WORKSPACE_TRANSLATE_X";
export const SET_WORKSPACE_TRANSLATE_Y = "SET_WORKSPACE_TRANSLATE_Y";
